import type { TemplateConfig, TemplateStyleId } from '../types/template.js';

export const TEMPLATES: Record<TemplateStyleId, TemplateConfig> = {
  clean: {
    id: 'clean',
    name: 'Clean & Minimal',
    nameZh: '简约风格',
    backgroundColor: '#FFFFFF',
    textColor: '#1A1A1A',
    subtitleColor: '#666666',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'silver',
    screenshotScale: 0.7,
    compositionMode: 'flow-drift',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'tech-dark': {
    id: 'tech-dark',
    name: 'Tech Dark',
    nameZh: '科技暗色',
    backgroundColor: {
      type: 'linear',
      angle: 180,
      stops: [
        { color: '#0F0F1A', position: 0 },
        { color: '#1A1A2E', position: 100 },
      ],
    },
    textColor: '#FFFFFF',
    subtitleColor: '#A0A0B8',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'dark',
    screenshotScale: 0.7,
    compositionMode: 'story-slice',
    paddingTop: 8,
    paddingBottom: 4,
  },
  vibrant: {
    id: 'vibrant',
    name: 'Vibrant & Colorful',
    nameZh: '活力色彩',
    backgroundColor: {
      type: 'linear',
      angle: 135,
      stops: [
        { color: '#667EEA', position: 0 },
        { color: '#764BA2', position: 100 },
      ],
    },
    textColor: '#FFFFFF',
    subtitleColor: 'rgba(255,255,255,0.85)',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'none',
    screenshotScale: 0.75,
    compositionMode: 'flow-drift',
    paddingTop: 6,
    paddingBottom: 4,
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora Glow',
    nameZh: '极光渐变',
    backgroundColor: {
      type: 'linear',
      angle: 120,
      stops: [
        { color: '#0B132B', position: 0 },
        { color: '#1C2541', position: 36 },
        { color: '#5BC0BE', position: 100 },
      ],
    },
    textColor: '#F8FAFF',
    subtitleColor: 'rgba(248,250,255,0.82)',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'dark',
    screenshotScale: 0.72,
    compositionMode: 'story-slice',
    paddingTop: 7,
    paddingBottom: 4,
  },
  'sunset-glow': {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    nameZh: '日落暖调',
    backgroundColor: {
      type: 'linear',
      angle: 130,
      stops: [
        { color: '#FF9A8B', position: 0 },
        { color: '#FF6A88', position: 52 },
        { color: '#FF99AC', position: 100 },
      ],
    },
    textColor: '#FFFFFF',
    subtitleColor: 'rgba(255,255,255,0.9)',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'none',
    screenshotScale: 0.74,
    compositionMode: 'flow-drift',
    paddingTop: 6,
    paddingBottom: 4,
  },
  'forest-mist': {
    id: 'forest-mist',
    name: 'Forest Mist',
    nameZh: '森系清新',
    backgroundColor: {
      type: 'linear',
      angle: 170,
      stops: [
        { color: '#E6F4EA', position: 0 },
        { color: '#CDEAD5', position: 55 },
        { color: '#A8DDB5', position: 100 },
      ],
    },
    textColor: '#1B4332',
    subtitleColor: '#2D6A4F',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'silver',
    screenshotScale: 0.7,
    compositionMode: 'flow-drift',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'rose-gold': {
    id: 'rose-gold',
    name: 'Rose Gold',
    nameZh: '玫瑰金质感',
    backgroundColor: {
      type: 'linear',
      angle: 145,
      stops: [
        { color: '#FFF6F0', position: 0 },
        { color: '#FAD4D8', position: 60 },
        { color: '#E8B4B8', position: 100 },
      ],
    },
    textColor: '#5E2B3A',
    subtitleColor: '#7A3E52',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'silver',
    screenshotScale: 0.7,
    compositionMode: 'flow-drift',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'monochrome-bold': {
    id: 'monochrome-bold',
    name: 'Monochrome Bold',
    nameZh: '黑白高对比',
    backgroundColor: {
      type: 'linear',
      angle: 180,
      stops: [
        { color: '#0F1115', position: 0 },
        { color: '#2A2F3A', position: 100 },
      ],
    },
    textColor: '#F8FAFC',
    subtitleColor: '#D8DEE9',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'dark',
    screenshotScale: 0.71,
    compositionMode: 'story-slice',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'ocean-breeze': {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    nameZh: '海盐清蓝',
    backgroundColor: {
      type: 'linear',
      angle: 155,
      stops: [
        { color: '#E0F7FA', position: 0 },
        { color: '#90E0EF', position: 58 },
        { color: '#48CAE4', position: 100 },
      ],
    },
    textColor: '#023047',
    subtitleColor: '#03506F',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'silver',
    screenshotScale: 0.7,
    compositionMode: 'flow-drift',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'neon-pulse': {
    id: 'neon-pulse',
    name: 'Neon Pulse',
    nameZh: '霓虹脉冲',
    backgroundColor: {
      type: 'linear',
      angle: 135,
      stops: [
        { color: '#09090F', position: 0 },
        { color: '#15162B', position: 46 },
        { color: '#00E5FF', position: 100 },
      ],
    },
    textColor: '#F7FAFF',
    subtitleColor: 'rgba(247,250,255,0.85)',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'dark',
    screenshotScale: 0.72,
    compositionMode: 'story-slice',
    paddingTop: 7,
    paddingBottom: 4,
  },
  'lavender-dream': {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    nameZh: '薰衣草梦境',
    backgroundColor: {
      type: 'linear',
      angle: 160,
      stops: [
        { color: '#F5F3FF', position: 0 },
        { color: '#E9D5FF', position: 56 },
        { color: '#D8B4FE', position: 100 },
      ],
    },
    textColor: '#4C1D95',
    subtitleColor: '#6D28D9',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'silver',
    screenshotScale: 0.72,
    compositionMode: 'flow-drift',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'desert-sand': {
    id: 'desert-sand',
    name: 'Desert Sand',
    nameZh: '沙漠暖金',
    backgroundColor: {
      type: 'linear',
      angle: 175,
      stops: [
        { color: '#FFF7ED', position: 0 },
        { color: '#FED7AA', position: 58 },
        { color: '#FDBA74', position: 100 },
      ],
    },
    textColor: '#7C2D12',
    subtitleColor: '#9A3412',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'silver',
    screenshotScale: 0.7,
    compositionMode: 'flow-drift',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'midnight-purple': {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    nameZh: '午夜紫电',
    backgroundColor: {
      type: 'linear',
      angle: 140,
      stops: [
        { color: '#140A2E', position: 0 },
        { color: '#2E1065', position: 52 },
        { color: '#7C3AED', position: 100 },
      ],
    },
    textColor: '#F8F5FF',
    subtitleColor: '#D9C8FF',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'dark',
    screenshotScale: 0.71,
    compositionMode: 'story-slice',
    paddingTop: 8,
    paddingBottom: 4,
  },
  'candy-pop': {
    id: 'candy-pop',
    name: 'Candy Pop',
    nameZh: '糖果流行',
    backgroundColor: {
      type: 'linear',
      angle: 132,
      stops: [
        { color: '#FF5EA8', position: 0 },
        { color: '#FF86C8', position: 45 },
        { color: '#7C9CFF', position: 100 },
      ],
    },
    textColor: '#FFFFFF',
    subtitleColor: 'rgba(255,255,255,0.9)',
    fontFamily: 'Inter',
    fontFamilyZh: 'Noto Sans CJK SC',
    textPosition: 'top',
    textAlignment: 'center',
    deviceFrameStyle: 'none',
    screenshotScale: 0.75,
    compositionMode: 'flow-drift',
    paddingTop: 6,
    paddingBottom: 4,
  },
};
